import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/css/globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen bg-linear-to-br from-purple-50 via-pink-50 to-blue-50 h-full flex flex-col">
          <Header />

          {children}

          <Footer />
        </main>
      </body>
    </html>
  );
}
